### ISSUE TITLE
FTGLDemo crashes as soon as I enter ü

### ISSUE THREAD

**Issue by krux02** [frankheckenbach/ftgl#15]
I tried the demo, and it crashes as soon as I enter `ü`. I am not suggesting this character must be supported, but at least it shouldn't crash the application if a letter isn't supported.

**Comment by frankheckenbach** [comment]
Actually, I don't use FTGL anymore (see #10). But fortunately, this was only a bug in the demos and easy to fix. They simply didn't handle non-ASCII keys at all. (Your timing was very lucky, BTW -- I had just worked on UTF-8 handling code in the past few days, so it was easy for me to fix right now.) Note, it still only handles Latin1 characters (i.e. up to codepoint 255). This seems to be a limitation of glutKeyboardFunc that the demos use, unrelated to FTGL which should support all Unicode characters.
