### ISSUE TITLE
there is no atomic in visual C++ versions 7,8,9,10 of std::atomic!

### ISSUE THREAD

**Issue by carlweiss32** [frankheckenbach/ftgl#21]
In Version 2.4.0, there is a build for Visual C 7,8,9, however, these versions of Visual C++ do not have #include <atomic>, is there a fix for this?
Atomic only exists in version 11 of Visual C

**Comment by frankheckenbach** [comment]
Note this repo isn't really maintained anymore (see https://github.com/frankheckenbach/ftgl/issues/10). You might want to try this fork: https://github.com/HamzaM3/ftgl

**Comment by carlweiss32** [comment]
Okay, thanks.
